name: RL4RL
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - libffi=3.4.6
  - liblzma=5.6.4
  - libsqlite=3.48.0
  - libzlib=1.3.1
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.10.16
  - setuptools=75.8.0
  - tk=8.6.13
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.42.34433
  - wheel=0.45.1
  - pip:
      - annotated-types==0.7.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - docker-pycreds==0.4.0
      - filelock==3.13.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gym==0.26.2
      - gym-notices==0.0.8
      - idna==3.10
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - pillow==11.0.0
      - platformdirs==4.3.6
      - protobuf==5.29.3
      - psutil==6.1.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rlgym==2.0.0
      - rlgym-api==2.0.0
      - rlgym-ppo==1.3.13
      - rlgym-rocket-league==2.0.0
      - rlviser-py==0.6.9
      - rocketsim==2.1.1.post1
      - sentry-sdk==2.21.0
      - setproctitle==1.3.4
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - wandb==0.19.6
